#!/usr/bin/env bash
set -euo pipefail

# --- Codex Swarm Agent Runner ---
# Generated by codex-swarm skill. Do not edit manually.

AGENT_ID="{{AGENT_ID}}"
AGENT_DIR="{{AGENT_DIR}}"
REPO_DIR="{{REPO_DIR}}"
SESSION_DIR="{{SESSION_DIR}}"
MODEL_FLAG="{{MODEL_FLAG}}"

STATUS_FILE="${AGENT_DIR}/status"
OUTPUT_FILE="${AGENT_DIR}/output.jsonl"
RESULT_FILE="${AGENT_DIR}/result.txt"
PROMPT_FILE="${AGENT_DIR}/prompt.txt"

# Write final status on exit
cleanup() {
    local exit_code=$?
    if [ $exit_code -eq 0 ]; then
        echo "completed" > "$STATUS_FILE"
    else
        echo "failed" > "$STATUS_FILE"
    fi
    echo "[${AGENT_ID}] Exited with code ${exit_code}" >&2
}
trap cleanup EXIT

# Mark as running
echo "running" > "$STATUS_FILE"

# Read prompt from file to avoid shell escaping issues
if [ ! -f "$PROMPT_FILE" ]; then
    echo "[${AGENT_ID}] ERROR: prompt.txt not found at ${PROMPT_FILE}" >&2
    exit 1
fi

PROMPT=$(cat "$PROMPT_FILE")

echo "[${AGENT_ID}] Starting codex agent in ${REPO_DIR}" >&2
echo "[${AGENT_ID}] Prompt: ${PROMPT}" >&2

# Run codex in full-auto mode with JSON output
# shellcheck disable=SC2086
codex exec \
    --full-auto \
    --json \
    $MODEL_FLAG \
    -C "$REPO_DIR" \
    -o "$RESULT_FILE" \
    "$PROMPT" \
    2>&1 | tee "$OUTPUT_FILE"
