#!/usr/bin/env bash
set -euo pipefail

# --- Plan-Build Session Runner ---
# Generated by plan-build skill. Do not edit manually.
#
# This runs a PERSISTENT interactive Codex session in a Zellij pane.
# Unlike codex exec (stateless), this preserves codebase context across
# iterations so Codex doesn't have to re-analyze the repo each time.

SESSION_DIR="{{SESSION_DIR}}"
REPO_DIR="{{REPO_DIR}}"
INITIAL_ITERATION="{{ITERATION}}"
MODEL_FLAG="{{MODEL_FLAG}}"

ITERATION_DIR="${SESSION_DIR}/${INITIAL_ITERATION}"
STATUS_FILE="${ITERATION_DIR}/status"
RESULT_FILE="${ITERATION_DIR}/result.txt"
PROMPT_FILE="${ITERATION_DIR}/prompt.txt"

# Write final status on exit
cleanup() {
    local exit_code=$?
    local current_status_file
    current_status_file=$(ls -t "${SESSION_DIR}"/iteration-*/status 2>/dev/null | head -1)
    if [ -n "$current_status_file" ]; then
        local current_status
        current_status=$(cat "$current_status_file" 2>/dev/null)
        if [ "$current_status" = "running" ]; then
            if [ $exit_code -eq 0 ]; then
                echo "completed" > "$current_status_file"
            else
                echo "failed" > "$current_status_file"
            fi
        fi
    fi
    echo "[plan-build] Session exited with code ${exit_code}" >&2
}
trap cleanup EXIT

# Mark initial iteration as running
echo "running" > "$STATUS_FILE"

# Read initial prompt
if [ ! -f "$PROMPT_FILE" ]; then
    echo "[plan-build] ERROR: prompt.txt not found at ${PROMPT_FILE}" >&2
    exit 1
fi

echo "[plan-build] Starting persistent Codex session in ${REPO_DIR}" >&2
echo "[plan-build] Initial iteration: ${INITIAL_ITERATION}" >&2

# Launch interactive Codex session with the initial prompt.
# The session stays alive in this pane — Claude sends follow-up
# prompts by writing to iteration-NN/prompt.txt and signaling
# via a FIFO or by sending keystrokes through Zellij.
cd "$REPO_DIR"
# shellcheck disable=SC2086
codex --full-auto $MODEL_FLAG
